# Learn more: https://docs.docker.com/compose/reference/
#
#   Build images: docker compose build
#      Start app: docker compose up app
# Start database: docker compose up db
# Run migrations: docker compose run migrate
#       Stop all: docker compose down (add -v to wipe db)
#

name: heatsync-members-server-prod

volumes:
  db_data:

networks:
  heatsync-network:
    driver: bridge
  
services:
  app:
    image: hammernshield/heatsynclabs-members-server:latest
    env_file:
      - .env
    environment:
      POSTGRES_HOST: db
    depends_on:
      - db
    ports:
      - '7777:8080'
    networks:
      - heatsync-network
    # user: '0' # uncomment to run as root for testing purposes even though Dockerfile defines 'vapor' user.
    command: ["serve", "--env", "production", "--hostname", "0.0.0.0", "--port", "8080"]
  web:
    image: hammernshield/heatsynclabs-members-site:latest
    depends_on:
      - app
    ports:
      - '7778:3000'
  migrate:
    image: hammernshield/heatsynclabs-members-server:latest
    env_file:
      - .env
    environment:
      POSTGRES_HOST: db
    depends_on:
      - db
    networks:
      - heatsync-network
    command: ["migrate", "--yes"]
    deploy:
      replicas: 0
  revert:
    image: hammernshield/heatsynclabs-members-server:latest
    env_file:
      - .env
    environment:
      POSTGRES_HOST: db
    depends_on:
      - db
    networks:
      - heatsync-network
    command: ["migrate", "--revert", "--yes"]
    deploy:
      replicas: 0
  db:
    image: postgres:16-alpine
    volumes:
      - db_data:/var/lib/postgresql/data/pgdata
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    env_file:
      - .env
    networks:
      - heatsync-network
  watchtower:
    image: containrrr/watchtower:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 --cleanup
    networks:
      - heatsync-network
